version: '3.8'

services: 
  postgresql:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: stock
    ports: 
      - 5432:5432
